### ISSUE TITLE
Office hours today

### ISSUE THREAD

**Issue by willpearse** [pearselab/r-world-AlexRego#3]
Hello Alex.

I realise we were going to talk today, but with my travel it's not going to work to talk at 9am your time. Can we re-schedule to later in the day - perhaps midday your time?

Thanks,

Will

**Comment by AlexRego** [comment]
No problemo! See you at noon-sh!

**Comment by willpearse** [comment]
This is unbelievable: I'm stuck in traffic leaving London. I should make it
back by 7 but right now anything could happen.

I will talk to you today - I will make this work. Thanks for your patience.

Will

**Comment by willpearse** [comment]
Thanks for being so flexible. I'm online now at https://appear.in/usubioprogramming
